name: Deploy Purkinje VM with Terraform

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Terraform Apply to GCP
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Decode GOOGLE_CREDENTIALS secret to file
        run: echo "$GOOGLE_CREDENTIALS" > ./src/gcp-key.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./src

      - name: Terraform Plan
        run: terraform plan -var="credentials_file=gcp-key.json"
        working-directory: ./src

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="credentials_file=gcp-key.json"
        working-directory: ./src
